name:                saved-for-reddit
version:             0.1.0.0
github:              "JBlackN/saved-for-reddit"
license:             MIT
author:              "Petr Schmied"
maintainer:          "peter9209@gmail.com"
copyright:           "2018 Petr Schmied"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/JBlackN/saved-for-reddit#readme>

dependencies:
- aeson
- base >= 4.7 && < 5
- base64-bytestring
- blaze-html
- blaze-markup
- bytestring
- clay
- http-conduit
- scotty
- text
- yaml

library:
  source-dirs: src

executables:
  saved-for-reddit-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - saved-for-reddit

tests:
  saved-for-reddit-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - saved-for-reddit
